language: node_js
node_js:
  - "9.3.0"
  - "8.9.3"
  - "7.10.1"
  - "6.12.2"
  - "5.12.0"
before_install:
  - sudo apt-get install -y libfuzzy-dev
  - npm install coffee-coverage istanbul coveralls
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
